services:
  nginx-frontend:
    image: nginx-frontend-image
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: nginx-frontend-container
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on:
      - nginx-frontend
