services:
  nginx-frontend:
    image: nginx-frontend-image
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: nginx-frontend-container
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api

  nginx-mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  nginx-redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data

  nginx-backend:
    image: nginx-backend-image
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: nginx-backend-container
    environment:
      - REDIS_URL=redis://nginx-redis:6379
      - MONGO_URL=mongodb://the_username:the_password@nginx-mongo:27017/the_database
    depends_on:
      - nginx-mongo
      - nginx-redis

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on:
      - nginx-frontend
