services:
  app:
    image: todo-frontend-image
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/urs/src/app
    ports:
      - 3000:3000
    container_name: todo-frontend-container
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
